### ISSUE TITLE
Error in configuring S3 as a backend.

### ISSUE THREAD

**Issue by deveshmehta** [claque2000/terraform-aws-tfbackend#6]
Hi,

Below is my terraform code to configure the S3 as backend. 

terraform {
  backend "s3" {
    encrypt        = true
    bucket         = "tfbackend-dev-mgmt-vpc"
    dynamodb_table = "tfbackend-dev-mgmt-vpc-lock"
    region         = "eu-west-2"
    key            = "dev-mgmt-vpc.tfstate"
  }
}

I am getting below error in configuring the S3 bucket created by your module. I am able to query and fetch details of AWS resources using awscli.

terraform init 

Initializing the backend...

Error configuring the backend "s3": NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Please update the configuration in your Terraform files to fix this error
then run this command again.

Could you please suggest what might be issue here? Is this because the S3 bucket require the KMS encryption ?

Thanks in advance
Devesh

**Comment by claque2000** [comment]
Hello,

Sorry for the late return. It seems to be the case, you don't put the kms_key_id in your backend configuration.

**Comment by deveshmehta** [comment]
I manage to solve this using following configuration

terraform {
  backend "s3" {
    bucket                  = "tfbackend-mgmt-rc"
    dynamodb_table          = "tfbackend-mgmt-rc-tfstatelock"
    region                  = "eu-west-2"
    key                     = "mgmt-rc.tfstate"
    shared_credentials_file = "/home/dmehta/.aws/credentials"
  }
}

**Comment by claque2000** [comment]
As it is solved on your side and the resolution seems to indicate a problem of credentials declaration, I close the issue.
